# -------
# Library
# -------

library:
  name: ComposePreferences
  api: 21
  github: MFlisar/ComposePreferences
  maven: io.github.mflisar.composepreferences
  maven-main-library: core
  multiplatform: true
  screenshots:
    - name: Changelog
      images:
        - ./screenshots/overview.jpg
  branch: main
  demo: true

# ------------
# Dependencies
# ------------

# optional
dependencies:
  compose:
    cmp: 1.7.1
    compose: 1.7.1
    material3: 1.3.1
    experimental: true

# -------------
# Module
# -------------

# GRUPPEN - optional: nur bei mehreren Modulen benötigt!
groups:
  - name: core
    label: Core
    gradle-comment: core 
  - name: screens
    label: Screens
    gradle-comment: screens
  - name: extensions
    label: Extensions
    gradle-comment: extensions

modules:
  - name: core
    group: core
    description: the core module to show a changelog
    optional: false
    platforms:
      android: true
      ios: true
      jvm: false
      info:
    dependencies: []
  - name: screen-bool
    group: screens
    description: a boolean preference screen
    optional: true
    platforms:
      android: true
      ios: true
      jvm: false
      info:
    dependencies: []
  - name: screen-button
    group: screens
    description: a button preference screen
    optional: true
    platforms:
      android: true
      ios: true
      jvm: false
      info:
    dependencies: []
  - name: screen-input
    group: screens
    description: an input preference screen
    optional: true
    platforms:
      android: true
      ios: true
      jvm: false
      info:
    dependencies:
      - name: ComposeDialogs
        link: https://github.com/MFlisar/ComposeDialogs
        version: 2.0.0
  - name: screen-color
    group: screens
    description: a color preference screen
    optional: true
    platforms:
      android: true
      ios: true
      jvm: false
      info:
    dependencies:
      - name: ComposeDialogs
        link: https://github.com/MFlisar/ComposeDialogs
        version: 2.0.0
  - name: screen-date
    group: screens
    description: a date preference screen
    optional: true
    platforms:
      android: true
      ios: true
      jvm: false
      info:
    dependencies:
      - name: ComposeDialogs
        link: https://github.com/MFlisar/ComposeDialogs
        version: 2.0.0
  - name: screen-time
    group: screens
    description: an input preference screen
    optional: true
    platforms:
      android: true
      ios: true
      jvm: false
      info:
    dependencies:
      - name: ComposeDialogs
        link: https://github.com/MFlisar/ComposeDialogs
        version: 2.0.0
  - name: screen-list
    group: screens
    description: a list preference screen
    optional: true
    platforms:
      android: true
      ios: true
      jvm: false
      info:
    dependencies:
      - name: ComposeDialogs
        link: https://github.com/MFlisar/ComposeDialogs
        version: 2.0.0
  - name: screen-number
    group: screens
    description: a number preference screen
    optional: true
    platforms:
      android: true
      ios: true
      jvm: false
      info:
    dependencies:
      - name: ComposeDialogs
        link: https://github.com/MFlisar/ComposeDialogs
        version: 2.0.0
  - name: extension-kotpreferences
    group: extensions
    description: an extension to use KotPreferences inside ComposePreferences
    optional: true
    platforms:
      android: true
      ios: true
      jvm: false
      info:
    dependencies:
      - name: ComposeDialogs
        link: https://github.com/MFlisar/KotPreferences
        version: 0.7.2