# -------
# Library
# -------

library:
  name: ComposePreferences
  api: 21
  github: MFlisar/ComposePreferences
  maven: io.github.mflisar.composepreferences
  maven-main-library: core
  multiplatform: true
  platforms:
    - jvm
    - android
    - ios
  screenshots: 
    - name: core
      images:
        - ./screenshots/core/info default.jpg
        - ./screenshots/core/info modern.jpg
        - ./screenshots/core/root default.jpg
        - ./screenshots/core/root modern.jpg
    - name: bool
      images:
        - ./screenshots/bool/bool default.jpg
        - ./screenshots/bool/bool modern.jpg
    - name: button
      images:
        - ./screenshots/button/button default.jpg
        - ./screenshots/button/button modern.jpg
    - name: color
      images:
        - ./screenshots/color/color default.jpg
        - ./screenshots/color/color dialog.jpg
        - ./screenshots/color/color dialog2.jpg
        - ./screenshots/color/color modern.jpg
    - name: date
      images:
        - ./screenshots/date/date default.jpg
        - ./screenshots/date/date dialog.jpg
        - ./screenshots/date/date modern.jpg
    - name: input
      images:
        - ./screenshots/input/input default.jpg
        - ./screenshots/input/input dialog.jpg
        - ./screenshots/input/input modern.jpg
    - name: list
      images:
        - ./screenshots/list/list default.jpg
        - ./screenshots/list/list dialog.jpg
        - ./screenshots/list/list dialog2.jpg
        - ./screenshots/list/list dropdown.jpg
        - ./screenshots/list/list modern.jpg
    - name: number
      images:
        - ./screenshots/number/number default.jpg
        - ./screenshots/number/number dialog.jpg
        - ./screenshots/number/number modern.jpg
    - name: time
      images:
        - ./screenshots/time/time default.jpg
        - ./screenshots/time/time dialog.jpg
        - ./screenshots/time/time modern.jpg
  branch: master
  demo: true

# ------------
# Dependencies
# ------------

dependencies:
  compose-multiplatform: 1.7.3 # https://github.com/JetBrains/compose-multiplatform/releases
  jetpack-compose-runtime: 1.7.6 # https://developer.android.com/jetpack/androidx/releases/compose-runtime
  jetpack-compose-material3: 1.3.1 # https://developer.android.com/jetpack/androidx/releases/compose-material3
  experimental: false

# ------------
# Groups
# ------------

groups:
  - name: core
    label: Core
    gradle-comment: core
  - name: modules
    label: Modules
    gradle-comment: modules
  - name: extensions
    label: Extensions
    gradle-comment: extensions

# ------------
# Modules
# ------------

modules:
  - name: core
    group: core
    description: provides all the basic preference classes and composables
    optional: false
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies:
      - name: ComposeDialogs
        link: https://github.com/MFlisar/ComposeDialogs
        version: 2.0.2
  - name: kotpreferences
    group: extensions
    description: 
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies:
      - name: KotPreferences
        link: https://github.com/MFlisar/KotPreferences
        version: 0.7.2
  - name: screen-bool
    group: modules
    description: provides a checkbox/switch preference screen
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies: []
  - name: screen-button
    group: modules
    description: provides a button preference screen
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies: []
  - name: screen-color
    group: modules
    description: provides a color picker preference screen
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies:
      - name: ComposeDialogs
        link: https://github.com/MFlisar/ComposeDialogs
        version: 2.0.2
  - name: screen-date
    group: modules
    description: provides a date picker preference screen
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies:
      - name: ComposeDialogs
        link: https://github.com/MFlisar/ComposeDialogs
        version: 2.0.2
  - name: screen-input
    group: modules
    description: provides a input dialog preference screen
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies:
      - name: ComposeDialogs
        link: https://github.com/MFlisar/ComposeDialogs
        version: 2.0.2
  - name: screen-list
    group: modules
    description: provides a list preference screen
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies:
      - name: ComposeDialogs
        link: https://github.com/MFlisar/ComposeDialogs
        version: 2.0.2
  - name: screen-number
    group: modules
    description: provides a number picker preference screen
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies:
      - name: ComposeDialogs
        link: https://github.com/MFlisar/ComposeDialogs
        version: 2.0.2
  - name: screen-time
    group: modules
    description: provides a time picker preference screen
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies:
      - name: ComposeDialogs
        link: https://github.com/MFlisar/ComposeDialogs
        version: 2.0.2