[versions]

accompanist = 			    "0.36.0"
moko-parcelize =            "0.9.0"

# mflisar
kotpreferences = 		    "0.7.2"
composedialogs =   		    "2.1.3"
toolbox =                   "2.5.0-alpha14" # for demo only!

[libraries]

drawablepainter = 		    	    { module = "com.google.accompanist:accompanist-drawablepainter", 		version.ref = "accompanist" }

moko-parcelize =                    { module = "dev.icerock.moko:parcelize", 		                        version.ref = "moko-parcelize" }

# mflisar
kotpreferences-core =			    { module = "io.github.mflisar.kotpreferences:core", 				    version.ref = "kotpreferences" }
kotpreferences-storage-datastore =  { module = "io.github.mflisar.kotpreferences:storage-datastore", 		version.ref = "kotpreferences" }
kotpreferences-extension-compose =  { module = "io.github.mflisar.kotpreferences:extension-compose", 		version.ref = "kotpreferences" }
composedialogs-core =			    { module = "io.github.mflisar.composedialogs:core", 				    version.ref = "composedialogs" }
composedialogs-dialog-list =	    { module = "io.github.mflisar.composedialogs:dialog-list", 				version.ref = "composedialogs" }
composedialogs-dialog-color =	    { module = "io.github.mflisar.composedialogs:dialog-color", 		    version.ref = "composedialogs" }
composedialogs-dialog-date =	    { module = "io.github.mflisar.composedialogs:dialog-date", 		        version.ref = "composedialogs" }
composedialogs-dialog-input =	    { module = "io.github.mflisar.composedialogs:dialog-input", 		    version.ref = "composedialogs" }
composedialogs-dialog-number =	    { module = "io.github.mflisar.composedialogs:dialog-number", 		    version.ref = "composedialogs" }
composedialogs-dialog-time =	    { module = "io.github.mflisar.composedialogs:dialog-time", 		        version.ref = "composedialogs" }
toolbox-core =                      { module = "io.github.mflisar.toolbox:core", 			                version.ref = "toolbox" }
toolbox-ui =                        { module = "io.github.mflisar.toolbox:ui", 			                    version.ref = "toolbox" }
toolbox-android-demo-app =          { module = "io.github.mflisar.toolbox:android-demo-app", 			    version.ref = "toolbox" }
toolbox-windows-app =               { module = "io.github.mflisar.toolbox:windows-app", 			        version.ref = "toolbox" }