[versions]

accompanist = 			    "0.36.0"
moko-parcelize =            "0.9.0"

# mflisar
kmp-template =              "1.2.2" # docu + demo only
kotpreferences =        	"1.0.1"  # todo
composedialogs =   		    "2.1.4"
toolbox =                   "2.5.1" # for demo only!

[plugins]

kmp-template-gradle-plugin =        { id = "io.github.mflisar.kmp-template.build-plugin",               version.ref = "kmp-template" }

[libraries]

drawablepainter = 		    	    { module = "com.google.accompanist:accompanist-drawablepainter", 		version.ref = "accompanist" }

moko-parcelize =                    { module = "dev.icerock.moko:parcelize", 		                        version.ref = "moko-parcelize" }

# mflisar
kmp-template-docs =                 { module = "io.github.mflisar.kmp-template:docs",                       version.ref = "kmp-template" }
kmp-template-open-source-demo =     { module = "io.github.mflisar.kmp-template:open-source-demo",           version.ref = "kmp-template" }
kotpreferences-core =			    { module = "io.github.mflisar.kotpreferences:core", 				    version.ref = "kotpreferences" }
kotpreferences-storage-datastore =  { module = "io.github.mflisar.kotpreferences:storage-datastore", 		version.ref = "kotpreferences" }
kotpreferences-extension-compose =  { module = "io.github.mflisar.kotpreferences:extension-compose", 		version.ref = "kotpreferences" }
composedialogs-core =			    { module = "io.github.mflisar.composedialogs:core", 				    version.ref = "composedialogs" }
composedialogs-dialog-list =	    { module = "io.github.mflisar.composedialogs:dialog-list", 				version.ref = "composedialogs" }
composedialogs-dialog-color =	    { module = "io.github.mflisar.composedialogs:dialog-color", 		    version.ref = "composedialogs" }
composedialogs-dialog-date =	    { module = "io.github.mflisar.composedialogs:dialog-date", 		        version.ref = "composedialogs" }
composedialogs-dialog-input =	    { module = "io.github.mflisar.composedialogs:dialog-input", 		    version.ref = "composedialogs" }
composedialogs-dialog-number =	    { module = "io.github.mflisar.composedialogs:dialog-number", 		    version.ref = "composedialogs" }
composedialogs-dialog-time =	    { module = "io.github.mflisar.composedialogs:dialog-time", 		        version.ref = "composedialogs" }
toolbox-core =                      { module = "io.github.mflisar.toolbox:core", 			                version.ref = "toolbox" }
toolbox-ui =                        { module = "io.github.mflisar.toolbox:ui", 			                    version.ref = "toolbox" }
toolbox-android-demo-app =          { module = "io.github.mflisar.toolbox:android-demo-app", 			    version.ref = "toolbox" }
toolbox-windows-app =               { module = "io.github.mflisar.toolbox:windows-app", 			        version.ref = "toolbox" }