[versions]

# general (local snapshot: "LOCAL-SNAPSHOT")
kmp-parcelize =             "2.0.0"
kotpreferences =        	"4.0.0"
composedialogs =   		    "4.0.0"

# plugins only
kmpicon-plugin =            "1.0.0"
kmpdevtools =               "7.9.7" # use the "devTools" task to change the version

# demos
democomposables =           "1.0.5"

[plugins]

# general
# --

# plugins only
kmpdevtools-buildplugin =           { id = "io.github.mflisar.kmpdevtools.plugins-build-gradle",        version.ref = "kmpdevtools" }
kmpicon-plugin =                    { id = "io.github.mflisar.kmpicon.plugin",                          version.ref = "kmpicon-plugin" }

[libraries]

# general
kmp-parcelize =                                 { module = "io.github.mflisar.kmpparcelize:library", 	                            version.ref = "kmp-parcelize" }
kotpreferences-core =               			{ module = "io.github.mflisar.kotpreferences:core", 								version.ref = "kotpreferences" }
kotpreferences-storage-datastore =     			{ module = "io.github.mflisar.kotpreferences:storage-datastore",      				version.ref = "kotpreferences" }
kotpreferences-storage-keyvalue =     			{ module = "io.github.mflisar.kotpreferences:storage-keyvalue",      				version.ref = "kotpreferences" }
kotpreferences-extension-compose =     		    { module = "io.github.mflisar.kotpreferences:extension-compose",      				version.ref = "kotpreferences" }
composedialogs-core =                      		{ module = "io.github.mflisar.composedialogs:core",      			                version.ref = "composedialogs" }
composedialogs-dialog-input =              		{ module = "io.github.mflisar.composedialogs:dialog-input",      			        version.ref = "composedialogs" }
composedialogs-dialog-number =             		{ module = "io.github.mflisar.composedialogs:dialog-number",      			        version.ref = "composedialogs" }
composedialogs-dialog-list =               		{ module = "io.github.mflisar.composedialogs:dialog-list",      			        version.ref = "composedialogs" }
composedialogs-dialog-time =               		{ module = "io.github.mflisar.composedialogs:dialog-time",      			        version.ref = "composedialogs" }
composedialogs-dialog-date =               		{ module = "io.github.mflisar.composedialogs:dialog-date",      			        version.ref = "composedialogs" }
composedialogs-dialog-color =              		{ module = "io.github.mflisar.composedialogs:dialog-color",      			        version.ref = "composedialogs" }

# demos
democomposables =                               { module = "io.github.mflisar.democomposables:library",                             version.ref = "democomposables" }