# Java
java-version: 17

# Developer
developer:
  name: Michael Flisar
  mail: mflisar.development@gmail.com
  maven-id: mflisar
  github-user-name: MFlisar

# Project
project:
  namespace: com.michaelflisar.composepreferences
  
# Readme
readme:
  screenshots:
    exclude-root: false
    group-by-folder: true
    excluded-folders: [previews]
    excluded-images: []